KangSanLee24/hunsu-project

- src/post/entities/post-image.entity.ts
- src/post/entities/post.entity.ts
closed #9
게시판, 게시판 이미지 엔티티 생성
-
> 🎉 add : 게시판, 게시판 이미지  엔티티 생성

- package-lock.json
- package.json
- src/comment/comment.controller.ts
- src/comment/entities/comment.entity.ts
- src/dislike/entities/comment-dislike.entity.ts
- src/dislike/entities/dislike.entity.ts
- src/dislike/entities/post-dislike.entity.ts
- src/like/entities/comment-like.entity.ts
- src/like/entities/like.entity.ts
- src/like/entities/post-like.entity.ts
- src/post/entities/post.entity.ts
#3 
post 엔티티에 관계 추가
comment, like, dislike 엔티티 작성
> 3 feature comment, like, distlike 엔티티 작성

- src/recomment/recomment.controller.ts
- src/recomment/recomment.service.ts
> chore: recomment url 변경

- src/comment/comment.controller.ts
- src/comment/comment.module.ts
- src/comment/comment.service.ts
- src/dislike/entities/comment-dislike.entity.ts
- src/dislike/entities/post-dislike.entity.ts
- src/like/entities/comment-like.entity.ts
- src/like/entities/post-like.entity.ts
- src/like/like.controller.ts
- src/like/like.module.ts
- src/like/like.service.ts
- src/recomment/dtos/create-recomment.dto.ts
- src/recomment/recomment.controller.ts
- src/recomment/recomment.service.ts
> 15 feature댓글좋아요controllerservice 댓글 좋아요 api

- src/auth/auth.controller.ts
- src/comment/comment.controller.ts
- src/comment/comment.service.ts
- src/comment/entities/comment.entity.ts
- src/recomment/recomment.controller.ts
> 28 feature싫어요controllerservice싫어요api

- .env.example
- package-lock.json
- package.json
- src/app.module.ts
- src/auth/auth.controller.ts
- src/auth/auth.module.ts
- src/auth/auth.service.ts
- src/auth/dtos/verify-email.dto.ts
- src/auth/entities/auth.entity.ts
- src/auth/entities/refresh-token.entity.ts
- src/auth/guards/jwt.strategy.ts
- src/auth/guards/re-token.guard.ts
- src/configs/env-validation.config.ts
- src/constants/auth-message.constant.ts
- src/decorators/log-in.decorator.ts
- src/decorators/token.decorator.ts
- src/mail/entities/verify-email.entity.ts
- src/mail/mail.controller.ts
- src/mail/mail.module.ts
- src/mail/mail.service.ts
- src/user/entities/point-log.entity.ts
- src/user/entities/point.entity.ts
- src/user/entities/user.entity.ts
closed #14 
- 토큰재발급 API
- 로그아웃 API
- 인증메일전송 API
- 이메일인증 API
> 14 featureauthcontrollerservice 토큰 재발급 로그아웃 api

- src/dislike/entities/post-dislike.entity.ts
- src/post/entities/post.entity.ts
> 34 bugfixpost dislike 엔티티수정

- client/src/pages/chat-list/chat-list.js
- client/src/pages/chat-room/chat.js
- src/chat/chat.controller.ts
- src/chat/chat.service.ts
- src/events/events.gateway.ts
> 40 feature채팅controllerserviceclient 채팅api

- .env.example
- package.json
> 48 featureauthcontrollyerservice env.example 추가 + package.json 오류 수정

- front/html/main.html
- front/html/post-list.html
- front/js/auth/email-confirmation.js
- front/js/auth/log-in.js
- front/js/auth/sign-up.js
- front/js/post/post-list.js
- front/styles/main.css
- front/styles/post-list.css
- front/styles/style.css
closed #72 
프론트엔드 게시글 목록 페이지
이슈에 적어놨습니다.
> 72 featurefe게시글목록조회

- src/constants/post-message.constant.ts
- src/post/post.controller.ts
- src/post/post.service.ts
- src/user/user.service.ts
> 74 featurepostcontrollyerservicedto 게시글 강제 삭제

- front/html/chat-list.html
- front/js/chat/chat-search.js
- front/js/chat/chat.js
- front/styles/chat.css
- src/chat/chat.controller.ts
- src/chat/chat.service.ts
- src/events/events.gateway.ts
-  채팅 검색 완료
- 채팅 입장/퇴장 알림
- 채팅 이미지 전송 버그 수정
- 채팅 마지막 시간 update 수정
> 70 feature채팅채팅febe 채팅구현

- front/js/post/post-list.js
> ✨ update:게시글목록페이지에서pagination추가

- src/aws/aws.service.ts
- src/comment/entities/comment.entity.ts
- src/constants/post-message.constant.ts
- src/dislike/entities/post-dislike.entity.ts
- src/post/entities/post-image.entity.ts
- src/post/post.controller.ts
- src/post/post.service.ts
> 82 feature게시글controllerservice s3 이미지 데이터 삭제 구현

- src/comment/comment.service.ts
- src/constants/comment-message.constant.ts
- src/constants/post-message.constant.ts
- src/dislike/dislike.controller.ts
- src/dislike/dislike.module.ts
- src/dislike/dislike.service.ts
- src/like/like.controller.ts
- src/like/like.module.ts
- src/like/like.service.ts
> 84 featurepostcontrollerservice 게시글 싫어요 시리즈 api

- front/html/post-detail.html
- front/js/post/comments.js
- front/js/post/post-detail.js
- front/js/post/post-list.js
- front/styles/post-detail.css
- src/comment/comment.service.ts
> 89 featurefe게시글상세페이지댓글작성

- src/app.module.ts
> bugfix:스케줄러 모듈 수정

- src/auth/auth.module.ts
- src/auth/auth.service.ts
- src/chat/chat.controller.ts
- src/comment/comment.module.ts
- src/comment/comment.service.ts
- src/constants/auth-message.constant.ts
- src/dislike/dislike.controller.ts
- src/like/like.controller.ts
- src/like/like.module.ts
- src/like/like.service.ts
- src/point/point.module.ts
- src/point/point.service.ts
- src/post/post.module.ts
- src/post/post.service.ts
- src/recomment/recomment.controller.ts
- src/recomment/recomment.module.ts
- src/recomment/recomment.service.ts
> 101 featurebackend포인트획득방법추가

- src/chat/chat.controller.ts
- src/chat/chat.service.ts
- src/events/events.gateway.ts
#105 
- 채팅 나가기 소켓 완료
- 채팅 삭제 소켓 완료
> 105 feature채팅service 채팅나가기

- front/html/chat-list.html
- front/js/chat/chat-search.js
- front/js/chat/chat.js
- front/styles/chat-list.css
- src/chat/chat.controller.ts
- src/chat/chat.service.ts
- 조회 로직 / fe 수정
- 채팅방 만들기 fe 수정
> 110 feature채팅조회fe 조회fe

- .env.example
- front/config/config.js
- front/html/alarm.html
- front/html/chat-list.html
- front/html/main.html
- front/html/post-detail.html
- front/html/post-list.html
- front/js/alarm/alarm.js
- front/styles/alarm.css
- front/styles/style.css
- src/alarm/alarm.controller.ts
- src/alarm/alarm.service.ts
- src/alarm/dto/find-all-alarms.dto.ts
- src/comment/comment.service.ts
- src/constants/alarm-message.constant.ts
- src/recomment/recomment.service.ts
> 92 featurefrontendetc 프론트엔드 - 알람

- front/html/chat-list.html
- front/html/chat.html
- front/html/main.html
- front/html/post-detail.html
- front/html/post-list.html
> feat: footer 아이콘 추가

- front/html/alarm.html
- front/html/chat-list.html
- front/html/chat.html
- front/html/main.html
- front/html/post-detail.html
- front/html/post-list.html
- front/js/main/header.js
- front/js/main/main.js
> 113 featurefront메인페이지 accesstoken유효한지체크

- front/js/alarm/alarm.js
- front/js/common/elapsed-time.js
- front/js/post/comments.js
- front/js/post/post-list.js
> ✨ update:시간표시함수elapsedTime를 common폴더로 이동 및 다른 js에 적용.

- src/chat/chat.controller.ts
- src/chat/chat.service.ts
#126 
- hot live chat top (num) 조회 api
> feat:hotlivechat 조회 api

- front/js/post/post-list.js
- src/decorators/count-like.decorator.ts
- src/post/dtos/find-all-posts.dto.ts
- src/post/entities/post.entity.ts
- src/post/post.controller.ts
- src/post/post.service.ts
> 122 bugfixbacketc

- front/html/post-detail.html
- front/js/post/comments.js
- front/styles/post-detail.css
- src/post/post.controller.ts
closed #124 
댓글 좋아요 싫어요 버튼 생성, 연결 함
css는 제대로 적용이 안되어짐;
-
> 124 featurefrontendfrontend 댓글 좋아요 싫어요 버튼 생성

- src/chat/chat.controller.ts
- src/hashtag/hashtag.controller.ts
- src/hashtag/hashtag.service.ts
- src/point/point.controller.ts
- src/point/point.service.ts
#130 
- 누적 포인트 랭킹 조회 api
- 주간 포인트 랭킹 조회 api
- 주간 해시태그 랭킹 조회 api
> 130 feature랭킹service 랭킹api

- front/config/config.js
- front/html/post-create.html
- front/html/post-detail.html
- front/html/post-list.html
- front/js/post/post-create.js
- front/js/post/post-detail.js
- front/styles/post-create.css
- package-lock.json
- package.json
- src/hashtag/hashtag.service.ts
- src/main.ts
- src/post/post.controller.ts
- src/post/post.service.ts
> 129 featurefrontend게시글생성페이지기초세팅

- front/js/chat/chat.js
- front/styles/chat-list.css
- src/chat/chat.service.ts
- src/events/events.gateway.ts
#136 
- 사진 고정 버그 수정
- 방장 입장 시 멤버 추가(2명으로 되는 부분) 버그 수정
- DB타임으로 변경
- 방장이 채팅방 나갈 시 , 채팅방 멤버들에게 알림 전송, 채팅 리스트 페이지로 이동
- 채팅방 삭제 로직 트랜잭션으로 변경
> 136 bugfix채팅 채팅fix

- src/chat/chat.service.ts
- src/point/point.service.ts
#141 
- 주간랭킹 기준 변경
- 매주 일요일~토요일 집계
> 141 refactor랭킹 주간포인트랭킹

- front/html/post-create.html
- front/js/auth/sign-up.js
- front/js/common/header.js
- front/js/post/comments.js
- front/js/post/post-create.js
- front/js/post/post-detail.js
- src/auth/auth.controller.ts
- src/aws/aws.service.ts
- src/post/dtos/create-post.dto.ts
- src/post/dtos/update-post.dto.ts
- src/post/post.service.ts
> 142 featurebackpost이미지관리로직

- .env.example
- front/config/config.js
- src/main.ts
> ✨ update: 1차배포0.15

- scripts/run.sh
> ✨ update: 1차배포0.22

- .github/workflows/cd.yml
- scripts/run.sh
> ✨ update: 1차배포0.23

- front/html/post-list.html
- front/js/common/header.js
> 글쓰기 버튼 수정2

- front/js/common/elapsed-time.js
- front/js/main/main.js
> fix : 시간 보정 9시간 제거

- front/html/log-in.html
- front/styles/log-in.css
> 159 featurefrontend로그인 로그인 화면 회원가입메인루트 추가

- front/js/chat/chat.js
- src/chat/chat.service.ts
- src/events/events.gateway.ts
#158 
- 중간 입장자에게도 이미지 상단 고정 보여줌
> 158 refactor채팅 이미지고정

- front/js/main/main.js
- src/comment/comment.service.ts
- src/point/point.service.ts
- src/recomment/recomment.service.ts
1. 자기 자신이 쓴 글에 댓글을 달았을 때 알람이 가지 않도록 수정
2. 자기 자신이 쓴 댓글에 대댓글을 달았을 때 알람이 가지 않도록 수정
3. 타인이 쓴 게시글에 댓글이 달렸는데 간헐적으로 제3자에게 알람이 가는 현상 수정
closed #164 
-
> fix: 알람 버그 수정 (내용)

- front/html/post-create.html
- front/html/post-list.html
- front/js/post/post-create.js
- front/js/post/post-detail.js
- src/point/point.service.ts
> 160 featurefront게시글생성페이지

- src/constants/post-message.constant.ts
- src/dislike/dislike.controller.ts
- src/dislike/dislike.module.ts
- src/dislike/dislike.service.ts
- src/like/like.controller.ts
- src/like/like.module.ts
- src/like/like.service.ts
1. 내가 이미 좋아요/싫어요 누른 상태인지 조회하는 API
2. 좋아요/싫어요 클릭 API (기존 좋아요 생성+삭제 통합,
기존 싫어요 생성+삭제 통합)
3. 좋아요/싫어요 크로스배팅 되는 문제는 해결 못했음. (순환오류발생)
이 부분은 프론트에서 막아주면 될 듯.
closed #170 
-
> feat: 게시글 좋아요/싫어요 관련 API들

- src/dislike/dislike.service.ts
> feat: 오타 수정

- front/html/post-detail.html
- front/js/post/comments.js
- front/js/post/post-detail.js
- front/styles/post-detail.css
- src/dislike/dislike.controller.ts
- src/like/like.controller.ts
- src/like/like.service.ts
프론트엔드 + 백엔드 수정
closed #178 
-프론트엔드 + 백엔드 수정(API변경)
> feat: 게시글 좋아요/싫어요 클릭

- front/html/post-detail.html
- front/js/post/post-detail.js
> 175 featurefrontend게시글상세페이지

- front/js/chat/chat.js
- front/styles/chat.css
- src/chat/chat.service.ts
- src/events/events.gateway.ts
#167 
- 채팅 방장 나가기 오류처리
- 삭제된 채팅방 오류처리
- 채팅방 새로고침 오류처리
- 채팅시간 추가
> 167 refactor채팅 나가기새로고침

- src/auth/auth.service.ts
> bugfix:회원가입시이메일발송에await삭제

- front/html/my-page.html
- front/html/update-profile.html
- front/js/my-page/my-page.js
- front/js/user/update-profile.js
- front/styles/my-page.css
- front/styles/update-profile.css
> 171 featurefrontend내 정보 수정 닉네임 변경 및 페이지

- front/js/post/comments.js
- front/js/post/post-detail.js
- src/dislike/dislike.controller.ts
- src/dislike/dislike.service.ts
- src/like/like.controller.ts
- src/like/like.service.ts
> 180 featurecommentslikedislike 백엔드+프론트엔드 수정

- front/html/sign-up.html
- front/styles/sign-up.css
> 회원가입 홈으로 버튼 진행 완료

- .github/workflows/cd.yml
> deploy:2차배포

- front/html/main.html
- front/js/auth/log-in-naver.js
- front/js/common/header.js
- src/post/post.service.ts
> fix: SSE버그수정 및 네이버로그인 버그 수정

- front/config/config.js
- front/html/post-create.html
- front/js/chat/chat.js
- front/js/main/main.js
- front/js/post/post-detail.js
- src/main.ts
closed #200 
게시글에 줄바뀜을 정상적으로 인지하지 못하는 상태 수정 
2차 배포를 위해 `localhost -> IP` 로 바꿧던 부분 원복.
> 🩹 fix:개발용 설정+게시글버그수정

- front/config/config.js
- front/html/post-create.html
- front/js/alarm/alarm.js
- front/js/chat/chat.js
- front/js/main/main.js
> ✨ update:url수정

- front/js/post/comments.js
- front/js/post/post-detail.js
- src/comment/comment.controller.ts
- src/comment/comment.service.ts
- src/constants/comment-message.constant.ts
- src/constants/post-message.constant.ts
- src/post/post.controller.ts
- src/post/post.service.ts
> feat: 좋아요/싫어요 크로스클릭 안되도록

- src/comment/comment.service.ts
- src/point/point.service.ts
- src/post/post.service.ts
closed #210
게시글 삭제시 오류 발생 현상 수정
> 210 bugfixback포인트

- front/js/chat/chat.js
#224 
- 채팅방 입장시 로그인 여부 체크 -> 로그인페이지로 이동
- url로 바로 들어온 사용자도 로그인 여부 체크
> feat:채팅 입장시 로그인여부 체크로직 추가

- src/alarm/alarm.controller.ts
- src/alarm/alarm.module.ts
- src/alarm/alarm.service.ts
- src/app.controller.ts
- src/auth/auth.controller.ts
- src/chat/chat.controller.ts
- src/comment/comment.controller.ts
- src/comment/comment.service.ts
- src/hashtag/hashtag.controller.ts
- src/mail/mail.controller.ts
- src/main.ts
- src/point/point.controller.ts
- src/point/point.service.ts
- src/post/post.controller.ts
- src/post/post.service.ts
- src/recomment/recomment.controller.ts
- src/recomment/recomment.service.ts
- src/user/user.controller.ts
> 227 bugfixback코드리펙토링할 부분 체크

- front/js/alarm/alarm.js
- front/js/auth/email-confirmation.js
- front/js/common/header.js
- front/js/common/level-rank.js
- front/js/main/main.js
> refactor: 메시지 수정, 레벨표기오류, 메인페이지 채팅방연결

- front/html/my-page.html
- front/js/auth/sign-up.js
- front/js/my-page/my-page.js
- front/js/user/delete-profile.js
- front/js/user/update-profile.js
- front/styles/update-profile.css
> 249 featurefrontmypage기능추가

- front/js/common/header.js
- front/js/main/main.js
- front/styles/main.css
- src/alarm/alarm.service.ts
- src/chat/chat.module.ts
- src/chat/chat.service.ts
- src/events/events.module.ts
해시태그가 새롭게 카운트 되었을 때 SSE로 메인페이지 해시태그 랭크 데이터 값 변경시켜주기
closed #248 
-
> feat: SSE로 메인 페이지 해시태그 랭크 데이터 변경

- .github/workflows/cd.yml
- scripts/cd-error.sh
> 🩹 fix: node_modules도 폴더 옮기게 변경

- .github/workflows/cd.yml
- front/js/common/header.js
- scripts/cd-error.sh
> 254 deployver21

- .github/workflows/cd.yml
> 🩹 fix: uninstall dev dependence 추가

- front/html/change-password.html
- front/html/chat-list.html
- front/html/email-confirmation.html
- front/html/log-in-naver-cb.html
- front/js/auth/find-pw.js
> 🐛 bugfix:/static/관련 url 수정

- front/html/post-create.html
- front/js/post/post-create.js
- front/js/post/post-detail.js
- src/post/dtos/create-post.dto.ts
- src/post/dtos/update-post.dto.ts
- src/post/post.service.ts
> 268 bugfixfrontback게시글해시태그 1

- src/chat/chat.service.ts
해시태그 카운트에 변동이 생기더라도
1위~10위의 해시태그 명단과 카운트에는 변화가 없는 경우
변동된 레디스 데이터를 SSE차원에서 전송하지 않도록 차단하여
리소스 낭비를 막습니다.
closed #274 
- 최적화 이전
현재 해시태그 카운트에 변동이 생기면
메인페이지에 있는 모든 사용자에게
변동된 레디스 데이터가 전송되고,
데이터를 받게 된 사용자는
해시태그 랭킹표시를 새로 랜더링 합니다.
- 최적화 이후
해시태그 카운트에 변동이 생기더라도
1위~10위의 해시태그 명단과 카운트에는 변화가 없는 경우
변동된 레디스 데이터를 SSE차원에서 전송하지 않도록 차단하여
리소스 낭비를 막습니다.
> refactor: 해시태그 랭킹 자동반영 최적화

- front/js/post/comment-edit.js
- front/js/post/comments.js
- front/styles/post-detail.css
> ✨ update:댓글 수정 삭제 버튼 활성화

- front/js/common/header.js
- front/js/common/identify-user.js
- front/js/post/comments.js
- front/js/post/post-detail.js
- front/styles/post-detail.css
- src/chat/chat.service.ts
리팩토링
closed #277 
- 수정/삭제 버튼 만들기
- 수정/삭제 버튼 작동JS연결
- 내가 쓴 댓글/대댓글이 아니면 수정/삭제 버튼 비활성화
- 삭제된 댓글인 경우 수정/삭제 버튼 비활성화
- 비로그인 상태에서 좋아요/싫어요 누를 수 없게
- 대댓글 좋아요/싫어요 누르면 새로고침 되는 현상 수정
- 대댓글 달았을 때 대댓글 창이 닫히지 않게 수정
- 대댓글이 생겼을 때 대댓글 버튼의 숫자가 +1 되도록 수정
> feat: 댓글/대댓글 리팩토링

- src/chat/chat.service.ts
- src/chat/dto/update-chat.dto.ts
#280 
- 불필요한 update chat dto 삭제
> del:불필요한 dto 삭제

- front/js/alarm/alarm.js
- src/constants/alarm-message.constant.ts
> fix: 알람 이모지/메시지 수정

- src/chat/chat.service.ts
- src/events/events.gateway.ts
#284 
- 채팅 목록 시간 수정
- 채팅 내역 시간 수정
> fix:채팅 시간수정

- front/js/post/post-create.js
- src/post/post.service.ts
> 285 bugfixfrontback게시글

- front/html/post-detail.html
- front/js/post/comments.js
- front/styles/post-detail.css
> 291 refactorfrontend 커서포인터 설정

- src/comment/entities/comment-dislike.entity.ts
- src/comment/entities/comment-like.entity.ts
- src/post/entities/post-like.entity.ts
- src/post/entities/post.entity.ts
- src/post/post.service.ts
> 🐛 bugfix:게시글 삭제 API 오류 수정

- src/comment/comment.service.ts
- src/post/post.service.ts
- src/recomment/recomment.service.ts
> 🐛 bugfix:탈퇴한회원의 게시글,댓글 불러올 시 오류 수정

- src/events/events.gateway.ts
> bugfix:시간수정

- front/html/chat.html
- front/styles/chat.css
- src/chat/chat.service.ts
> 310 feature채팅멤버 목록조회

- front/html/chat.html
- front/js/chat/chat.js
- front/styles/chat.css
- src/chat/chat.controller.ts
- src/chat/chat.service.ts
- src/schedule/schedule.service.ts
> feat:멤버목록 조회 추가

- .github/workflows/cd.yml
> deploy 2.7.1

- .github/workflows/cd.yml
> deploy 2.7.2

- .github/workflows/cd.yml
> deploy 2.7.4

- .github/workflows/cd.yml
> deploy 2.7.5

- .github/workflows/cd.yml
> fix:.sentryclirc추가 0.6

- .github/workflows/cd.yml
> deploy 2.7.6

- .github/workflows/cd.yml
> fix:.sentryclirc추가 0.8

- package-lock.json
- package.json
- src/main.ts
- src/redis-io.adapter/redis-io.adapter.ts
#333 
- socket io redis adapter 추가
> feat:redis apadter

- .github/workflows/cd.yml
- package-lock.json
- package.json
- src/main.ts
- src/redis-io.adapter/redis-io.adapter.ts
- src/sentry/sentry-webhook.intersepter.ts
> deploy 2.7.8

- src/app.module.ts
- src/main.ts
- src/redis-io.adapter/redis-io.adapter.module.ts
- src/redis-io.adapter/redis-io.adapter.ts
- src/redis/redis.service.ts
- src/redis/sub.redis.service.ts
#333 
- socket io redis 연결 버그 수정
> fix:socket io redis 연결 버그 수정

- src/main.ts
> fix:cors 수정

- front/js/index/index.js
keyword encode 문제로 큰 따옴표 추가
${keyword} -> "${keyword}"
-
> keyword 큰 따옴포 수정

- front/js/chat/chat.js
- src/events/events.gateway.ts
> fix transports websocket 추가

- front/js/post/post-list.js
> fix: 게시판 목록 조회 버그 수정

- front/html/log-manager.html
- front/js/admin/log-manager.js
- front/js/alarm/alarm.js
- front/styles/log-manager.css
- src/configs/winston.config.ts
- src/log/dto/get-all-logs.dto.ts
- src/log/entities/log.entity.ts
- src/log/log.controller.ts
- src/log/log.service.ts
- src/schedule/schedule.module.ts
- src/schedule/schedule.service.ts
1. 로그매니저 (프론트엔드)
2. 로그 관련 API (목록조회/삭제/DB이전)
3. Cron 연결(1분마다 DB이전API)
closed #356
> feat: 로그관리기능들 추가

- front/html/alarm.html
- front/html/chat-list.html
- front/html/chat.html
- front/html/index.html
- front/html/log-manager.html
- front/html/my-page.html
- front/html/post-create.html
- front/html/post-detail.html
- front/html/post-list.html
- front/js/common/header.js
- front/styles/index.css
- front/styles/style.css
- src/log/log.controller.ts
1. 백엔드
- ADMIN RolesGuard 적용
2. 프론트엔드
- 모든 페이지 ADMIN 버튼 생성
- ADMIN 버튼 생성 조건 js 추가
- ADMIN 버튼 - 로그매너저 연결
> feat: 로그매니저 백엔드 롤스가드 적용 및 프론트 연결

- scripts/run.sh
> ✨ update:포트포워딩, 탬플릿자동업데이트 기능 추가

- src/chat/chat.service.ts
- src/chat/entities/chat-room.entity.ts
- src/events/events.gateway.ts
- src/schedule/schedule.service.ts
#364 
- 해시태그 저장소를 레디스로 옮김에 따라 채팅방 삭제 스케줄러 수정
- 기존 : 컬럼 업데이트 이후 스케줄러로 채팅방 삭제
- 변경 : 컬럼 업데이트 없이 바로 해당 채팅방 삭제 / chatroom entity의 컬럼 'isDeleted' 삭제 됐습니다.
> fix:채팅방 삭제 스케줄러 삭제

- scripts/run.sh
> 370 featurecicdauto scaling instanse auto terminate

- front/html/my-page.html
- front/js/auth/email-confirmation.js
- front/js/common/header.js
- front/js/index/index.js
- src/point/point.service.ts
메인페이지 해시태그 쇼핑 품목 순차배열
포인트 감산 로직 0점으로 수정
회원가입, 마이페이지에 포인트 획득치 표기
-
> 362 refactorfe 해시태그 쇼핑 목록 순차 실행

- .github/workflows/cd.yml
> fix: VM의 node버전 고정

- .github/workflows/cd.yml
> fix: VM의 node버전 다시 수정

- .github/workflows/cd.yml
#384 
- hotlivechat 조회 쿼리 버그 수정
> deploy 2.9.1

- src/chat/chat.service.ts
> deploy 2.9.2

- src/chat/chat.service.ts
#389 
- hot live chat 쿼리 최종 수정
> deploy 2.9.3
